scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: node-exporter
    scrape_interval: 30s
    static_configs:
    - targets: ["35.180.231.183:9100", "51.44.186.84:9100", "15.237.81.209:9100"]

  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
    - targets: ["35.180.231.183:9101", "192.168.0.11:9101"]