groups:

  - name: nginx_rules
    rules:
      - alert: NginxDown
        expr: up{job="nginx"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Le service Nginx est indisponible"
          description: "Nginx est en panne depuis plus d'une minute."

  - name: disk_usage_rules
    rules:
      - alert: DiskUsageHigh
        expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} < 0.2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Espace disque critique"
          description: "Le disque est rempli à plus de 80%."