all:
  children:
    moni:
      hosts:
        moni-observer:
          ansible_host: 13.38.40.82
          ansible_user: admin
          ansible_ssh_private_key_file: /home/engineer/.ssh/deploy_key
    target:
      hosts:
        moni-observer:
          ansible_host: 13.38.40.82
          ansible_user: admin
          ansible_ssh_private_key_file: /home/engineer/.ssh/deploy_key
        monitoring-frontend-1:
          ansible_host: 15.236.55.233
          ansible_user: admin
          ansible_ssh_private_key_file: /home/engineer/.ssh/deploy_key
        monitoring-backend-2:
          ansible_host: 15.188.79.160
          ansible_user: admin
          ansible_ssh_private_key_file: /home/engineer/.ssh/deploy_key