- name: update apt
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present

- name: Install  Docker keyrings
  shell: sudo install -m 0755 -d /etc/apt/keyrings

- name: Add Docker repository
  shell: sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc

- name: Edit Docker keyrings
  shell: sudo chmod a+r /etc/apt/keyrings/docker.asc

- name: Edit aptsources
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: update apt
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present


- name: Add docker to sudoers
  user:
    name: "admin"
    groups: ["sudo", "docker"]
    append: yes
    shell: /bin/bash
    create_home: yes

- name: Start and enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started
